version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: dazzling_engelbart
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local
