version: '3'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: samurai
      POSTGRES_USER: samurai
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/samurai
      KC_DB_USERNAME: samurai
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    command: start-dev

volumes:
  postgres_data: